name: Deploy

on:
  push:
    branches:
      - 21_1

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme: [ material.orange.light, generic.light ]

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install
      run: npm install

    - name: Set theme
      run: npm run set-theme -- ${{ matrix.theme }}

    - name: Build
      run: npm run build

    - name: Copy apps
      run: npm run copy-build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        branch: gh-pages
        folder: devextreme-rwa-demos
        target-folder: ${{ matrix.theme }}

