name: Deploy

on:
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Set themes matrix
      id: set-matrix
      run: |
        themes_json=`cat ./packages/metadata/themes.json`
        themes_json="${themes_json//$'\n'/''}"
        themes_json="${themes_json//$'\r'/''}"
        themes_json="${themes_json//$' '/''}"
        echo "matrix=$themes_json" >> $GITHUB_OUTPUT
  build:
    needs: set-matrix
    name: Build applications
    runs-on: ubuntu-latest
    env:
      CI: false
    strategy:
      matrix:
        theme: ${{fromJson(needs.set-matrix.outputs.matrix)}}
        mode: [ default, embedded ]

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set NPM version
      run: npm i npm@7 -g

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install
      run: npm install

    - name: Authenticate to GitHub Package
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      
    - name: Download Internal Packages
      run: |
        DEVEXTREME_INTERNAL_VERSION=$(npm pkg get dependencies.devextreme --workspaces=false | tr -d '"')
        npm pack @devexpress/devextreme-internal@$DEVEXTREME_INTERNAL_VERSION --registry https://npm.pkg.github.com
        npm pack @devexpress/devextreme-dist-internal@$DEVEXTREME_INTERNAL_VERSION --registry https://npm.pkg.github.com

    - name: Unpack devextreme-internal
      run: |
        DEVEXTREME_FILE_NAME=$(find . -name DevExpress-devextreme-internal-*.tgz)
        mkdir devextreme-internal-package
        cd ./devextreme-internal-package
        tar -xvzf ../$DEVEXTREME_FILE_NAME

    - name: Copy devextreme-internal
      run: | 
        rm -rf ./node_modules/devextreme/*
        mv ./devextreme-internal-package/package/* ./node_modules/devextreme
        rm -rf ./devextreme-internal-package 

    - name: Unpack devextreme-dist-internal
      run: |
        DEVEXTREME_DIST_FILE_NAME=$(find . -name DevExpress-devextreme-dist-internal-*.tgz)
        mkdir devextreme-dist-internal-package
        cd ./devextreme-dist-internal-package
        tar -xvzf ../$DEVEXTREME_DIST_FILE_NAME

    - name: Copy devextreme-dist-internal
      run: |
        rm -rf ./node_modules/devextreme-dist/*
        mv ./devextreme-dist-internal-package/package/* ./node_modules/devextreme-dist
        rm -rf ./devextreme-dist-internal-package

    - name: Set theme
      run: npm run set-theme -- ${{ matrix.theme }}

    - name: Set mode
      if: ${{ matrix.mode == 'embedded' }}
      run: npm run make-embedded-mode

    - name: Build
      run: npm run build

    - name: Copy apps
      run: npm run copy-build -- ${{ matrix.mode }} ${{ matrix.theme }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: devextreme-ui-template-gallery/

  build-shell:
    name: Build shell
    runs-on: ubuntu-latest

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set NPM version
      run: npm i npm@7 -g

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install
      run: npm install

    - name: Authenticate to GitHub Package
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

    - name: Download Internal Packages
      run: |
        DEVEXTREME_INTERNAL_VERSION=$(npm pkg get dependencies.devextreme --workspaces=false | tr -d '"')
        npm pack @devexpress/devextreme-internal@$DEVEXTREME_INTERNAL_VERSION --registry https://npm.pkg.github.com
        npm pack @devexpress/devextreme-dist-internal@$DEVEXTREME_INTERNAL_VERSION --registry https://npm.pkg.github.com

    - name: Unpack devextreme-internal
      run: |
        DEVEXTREME_FILE_NAME=$(find . -name DevExpress-devextreme-internal-*.tgz)
        mkdir devextreme-internal-package
        cd ./devextreme-internal-package
        tar -xvzf ../$DEVEXTREME_FILE_NAME

    - name: Copy devextreme-internal
      run: |
        rm -rf ./node_modules/devextreme/*
        mv ./devextreme-internal-package/package/* ./node_modules/devextreme
        rm -rf ./devextreme-internal-package

    - name: Unpack devextreme-dist-internal
      run: |
        DEVEXTREME_DIST_FILE_NAME=$(find . -name DevExpress-devextreme-dist-internal-*.tgz)
        mkdir devextreme-dist-internal-package
        cd ./devextreme-dist-internal-package
        tar -xvzf ../$DEVEXTREME_DIST_FILE_NAME

    - name: Copy devextreme-dist-internal
      run: |
        rm -rf ./node_modules/devextreme-dist/*
        mv ./devextreme-dist-internal-package/package/* ./node_modules/devextreme-dist
        rm -rf ./devextreme-dist-internal-package

    - name: Build Shell
      run: npm run build-shell
      working-directory: packages/shell

    - name: Copy apps
      run: npm run copy-shell

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: devextreme-ui-template-gallery/

  # deploy:
  #   name: Deploy
  #   needs: [build, build-shell]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Get sources
  #     uses: actions/checkout@v3

  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: build-artifacts
  #       path: devextreme-ui-template-gallery

  #   - name: Deploy in gh-pages
  #     uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
  #     with:
  #       branch: gh-pages
  #       folder: devextreme-ui-template-gallery
  #       target-folder: .

