name: Test

on: [push, pull_request]

jobs:
  test-meta:
    name: Test metadata
    runs-on: ubuntu-latest

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install for metadata
      run: npm install
      working-directory: packages/metadata

    - name: Test Metadata
      run: npm run test
      working-directory: packages/metadata

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set NPM version
      run: npm i npm@7 -g

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install
      run: npm install

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm run test
      working-directory: packages/testing

    - name: Copy screenshots artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ${{ github.workspace }}/packages/testing/testing/artifacts/compared-screenshots/*
        if-no-files-found: ignore
